In [13]:
import torch

In [14]:
a = torch.arange(12).view(4, 3)
print(a)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [15]:
a.size(-1)

3

In [3]:
a + 1

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [4]:
a.dtype

torch.int64

In [3]:
b = torch.arange(12, 24).view(4, 3)

In [4]:
b

tensor([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]])

In [5]:
c = torch.arange(24, 36).view(4, 3)

In [6]:
c

tensor([[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]])

In [7]:
t = [a, b, c]

In [8]:
type(t)

list

In [9]:
t

[tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]),
 tensor([[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]),
 tensor([[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]])]

In [10]:
t_stack = torch.stack(t, dim=1)

In [11]:
t_stack

tensor([[[ 0,  1,  2],
         [12, 13, 14],
         [24, 25, 26]],

        [[ 3,  4,  5],
         [15, 16, 17],
         [27, 28, 29]],

        [[ 6,  7,  8],
         [18, 19, 20],
         [30, 31, 32]],

        [[ 9, 10, 11],
         [21, 22, 23],
         [33, 34, 35]]])

In [13]:
t_stack.size()

torch.Size([4, 3, 3])

In [15]:
t_stack.size()[-1]

3

In [14]:
x = a.view(-1)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [16]:
lg = t_stack.view(-1, t_stack.size()[-1])

In [17]:
lg

tensor([[ 0,  1,  2],
        [12, 13, 14],
        [24, 25, 26],
        [ 3,  4,  5],
        [15, 16, 17],
        [27, 28, 29],
        [ 6,  7,  8],
        [18, 19, 20],
        [30, 31, 32],
        [ 9, 10, 11],
        [21, 22, 23],
        [33, 34, 35]])

In [18]:
import torch.nn.functional as F

In [19]:
target = torch.ones(12)

In [20]:
target

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
lg.dtype

torch.int64

In [23]:
lg = lg.float()

In [24]:
lg.dtype

torch.float32

In [25]:
target.dtype

torch.float32

In [27]:
target = target.long()

In [28]:
target.dtype

torch.int64

In [29]:
loss = F.cross_entropy(lg, target)

In [30]:
loss

tensor(1.4076)

In [31]:
probs = torch.softmax(lg, dim=1)

In [32]:
nll = -torch.log(probs)

In [33]:
nll.mean(dim=0)

tensor([2.4076, 1.4076, 0.4076])

加citation, 至少30篇
提及EMG只是一种方式
introduce deep learning in EMG generally, what's lost
labeled 模型在chatemg之前，general -> focus
chatemg放最后
每篇文章评论发现了什么，获得了什么，什么limit，
future plans -> methodology
加一个可视化的图表示计划带具体日期
motivation step by step
how the thesis is organized

在related work的最后，添加comment

最后加上可视化timeline

可以加入images说明
6 pages for related work
3 or 4 pages for intro
可以先介绍一些DL在其他方面的应用，然后转到EMG上的应用
我可以自己分类讨论，每个类别多篇文章
paragraph guiding steps