In [1]:
import yaml
import matplotlib.pyplot as plt
import numpy as np
from data_processing.preprocess import EMGPreprocessor


d:\anaconda\envs\potnet\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:

config_path = 'configs/ninapro_db5/full_train_lstm_w100_s5_2l.yaml'
with open(config_path, 'r') as file:
    config = yaml.safe_load(file)
    
preprocessor = EMGPreprocessor(config)
preprocessor.process()


Sliding windows data saved successfully at: datasets/windows/ninapro_db5\win100_step5.npy
The full windows data is of the shape (1270081, 100, 16).


array([[[  0.,  -1.,  -1., ...,   3.,   1.,   1.],
        [ -3.,  -3.,  -3., ...,  -2.,  -2.,  -2.],
        [ -2.,   0.,   0., ...,  -5.,  -2.,  -2.],
        ...,
        [  1.,  -1.,   0., ...,   0.,   1.,   0.],
        [  0.,   1.,  -2., ...,  -2.,  -2.,  -1.],
        [ -2.,  -1.,  -1., ...,  -2.,  -2.,  -4.]],

       [[ -1.,   2.,  -2., ...,  -2.,   3.,   4.],
        [  0.,  -2.,  -1., ...,   1.,  -3.,  -4.],
        [ -1.,  -2.,  -2., ...,  -1.,   0.,  -1.],
        ...,
        [ -2.,  -1.,   0., ...,  -2.,  -2.,   1.],
        [  0.,  -2.,   0., ...,  -3.,  -1.,  -2.],
        [  1.,   1.,   0., ...,   0.,  -1.,   0.]],

       [[ -3.,   1.,  -2., ...,  -2.,  -1.,  -2.],
        [  0.,   0.,   0., ...,   2.,  -3.,  -2.],
        [  2.,  -3.,  -2., ...,  -1.,  -3.,   1.],
        ...,
        [  0.,   2.,  -3., ...,  -4.,  -2.,  -2.],
        [  0.,  -2.,   0., ...,   0.,   0.,   0.],
        [ -1.,   3.,   0., ...,  -3.,  -3.,  -4.]],

       ...,

       [[ -2.,   0.,  -2

In [1]:
import numpy as np

In [2]:
data = np.load("datasets/windows/ninapro_db5/win200_step100.npy")

In [3]:
print(data)

[[[   0.   -1.   -1. ...    3.    1.    1.]
  [  -3.   -3.   -3. ...   -2.   -2.   -2.]
  [  -2.    0.    0. ...   -5.   -2.   -2.]
  ...
  [  -2.    2.    0. ...   -3.   -4.   -3.]
  [  -1.   -1.   -1. ...   -1.   -1.   -1.]
  [  -1.   -5.   -5. ...   -2.   -2.   -1.]]

 [[   0.   -4.   -1. ...   -2.    1.   -1.]
  [  -2.   -1.    0. ...    2.    1.    0.]
  [  -2.   -1.    0. ...   -2.   -2.    1.]
  ...
  [  -2.    0.    1. ...    0.   -2.   -3.]
  [  -2.   -3.   -1. ...   -2.   -2.   -1.]
  [  -1.   -2.    1. ...    2.   -1.   -1.]]

 [[  -1.   -2.   -2. ...   -4.   -5.   -4.]
  [   0.   -3.   -2. ...    0.    3.    2.]
  [   1.    0.    0. ...    0.    0.    1.]
  ...
  [   0.   -1.    0. ...   -1.    1.    2.]
  [  -6.    0.    0. ...   -2.   -4.   -1.]
  [  -1.   -2.   -3. ...   -1.   -4.   -7.]]

 ...

 [[ -35.    0.   -2. ...  -13.  -97.   17.]
  [ -18.  -21.    1. ...  -43.   24.  -22.]
  [  24.    4.   -2. ...   83.  -22.    1.]
  ...
  [  11.   29.   -9. ...   -7.   14.   6

In [4]:
import os

In [5]:
os.path.exists("datasets/windows/ninapro_db5")

True

In [6]:
os.path.isfile("datasets/windows/ninapro_db5/win200_step100.npy")

True

In [8]:
os.path.isfile("datasets/windows/ninapro_db5/win200_step10.npy")

False

In [36]:
from data_processing.load_raw_data import ninapro_loader, senic_loader
import yaml
import os

In [37]:
config_path = 'configs/ninapro_db5/full_train_transformer.yaml'
with open(config_path, 'r') as file:
    config = yaml.safe_load(file)

In [38]:
data_frames = senic_loader(config)

In [39]:
len(data_frames)

2310

In [40]:
data_frames[0].shape[0]

1627

In [1]:
from trainer.base_trainer import Trainer

d:\anaconda\envs\potnet\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
d:\anaconda\envs\potnet\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
import yaml

In [3]:
config_path = 'configs/senic/transformer.yaml'
with open(config_path, 'r') as file:
    config = yaml.safe_load(file)

In [4]:
config["train"]["enable_shuffle"]

False

In [5]:
from data_processing.preprocess import EMGPreprocessor

In [6]:
processor = EMGPreprocessor(config)

In [7]:
processor.load_data()

In [8]:
import numpy as np

In [9]:
processor.data_frames[0].to_numpy()[0]

array([-2., -3., -1., -3., -2.,  1., -1., -1.])

In [10]:
windows = processor.sliding_window()

In [11]:
windows[0].shape

(50, 8)

In [12]:
test_trainer = Trainer(config)

In [13]:
train_loader, val_loader = test_trainer.load_datasets()

The full windows data is of the shape (361610, 50, 8).


In [14]:
first_batch = next(iter(train_loader))

In [15]:
inputs, targets = first_batch
print("First Sample Input:", inputs[0])
print("First Sample Targets:", targets[0])

First Sample Input: tensor([[-2., -3., -1., -3., -2.,  1., -1., -1.],
        [-2., -5., -2.,  0., -1.,  0.,  0.,  0.],
        [ 4.,  8.,  2.,  0.,  2.,  0., -2., -1.],
        [-1., -2.,  0., -1.,  0., -1., -3., -2.],
        [-3., -2., -1., -3., -2., -5., -3.,  0.],
        [-2., -3., -2.,  1., -3.,  0.,  0., -2.],
        [ 1., -3.,  0.,  2.,  0.,  1.,  0.,  0.],
        [ 0.,  0., -2., -2., -1., -1., -2.,  1.],
        [ 0., -3.,  0., -1., -1., -2.,  0., -2.],
        [ 0.,  0.,  1., -1.,  0.,  1.,  2., -1.],
        [-1.,  1.,  0.,  0.,  0.,  1.,  1.,  3.],
        [ 0., -1.,  1., -2.,  0., -2., -3., -2.],
        [-3., -4., -2., -2., -1., -2., -3.,  0.],
        [ 0.,  1., -1., -1., -3., -3., -1., -1.],
        [-1., -1., -1.,  3.,  0.,  1.,  1., -1.],
        [-1., -3., -4., -1., -2.,  0., -1.,  0.],
        [-1., -5.,  0., -2., -1.,  0., -1., -1.],
        [ 2.,  7.,  3.,  0.,  0.,  0.,  0., -1.],
        [-2.,  3., -1.,  0., -1.,  1.,  1.,  1.],
        [-2., -2.,  0.,  1., -